catalog_name: mlops_dev
schema_name: efedanis
experiment_name_basic: /Shared/airline-reviews-basic

data_path: "/Volumes/mlops_dev/efedanis/data/airline_reviews.csv"
parameters:
  learning_rate: 0.01
  n_estimators: 500
  max_depth: 6

cat_features:
  - traveller_type
  - cabin

num_features:
  - seat_comfort
  - cabin_service
  - food_bev
  - entertainment
  - ground_service
  - value_for_money

target: recommended
