catalog_name: mlops_dev
schema_name: efedanis

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - seat_comfort
  - cabin_service
  - food_bev;entertainment
  - ground_service
  - value_for_money,

target: recommended
